import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const geistQuickSand = Quicksand({
  variable: "--font-geist-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params?: { slug?: string[] };
}>) {

  const pathname = "/" + (params?.slug?.join("/") ?? "");
  const asideWidth = pathname === "/" || pathname === "/login" ? "w-10" : "w-16";

  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${geistQuickSand.variable} antialiased`}
        style={{ background: "linear-gradient(121.61deg, #4292ED 0.55%, #ED4242 99.45%);" }}
      >
        <div className="flex-1 mr-10">
          <img src="/leftbg.svg" style={{ position: "absolute", zIndex: "-9999", height: "100vh", left: 0 }}></img>
          <img src="/rightbg.svg" style={{ position: "absolute", zIndex: "-9999", height: "100vh", right: 0 }}></img>
          {children}
        </div>

        <div className={`asideright fixed right-0 top-0 h-screen ${asideWidth} flex flex-col`}>
          <div className="clip-path-bottom bg-[var(--secondary)]" style={{ flex: "1.5" }}>
            <div className="aside-hover">Cinza</div>
          </div>

          <div className="aside-block bg-[var(--background)]" style={{ marginTop: "-50px" }}>
            <div className="aside-hover" style={{ color: "#000" }}>Branco</div>
          </div>

          <div className="aside-block bg-[var(--tertiary)]">
            <div className="aside-hover">Vermelho</div>
          </div>

          <div className="aside-block bg-[var(--primary)]">
            <div className="aside-hover">Azul</div>
          </div>

          <div className="aside-block black clip-path-top bg-[var(--foreground)]">
            <div className="aside-hover">Preto</div>
          </div>
        </div>

      </body>
    </html>
  );
}
