import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params?: { slug?: string[] };
}>) {

  const pathname = "/" + (params?.slug?.join("/") ?? "");
  const asideWidth = pathname === "/" || pathname === "/login" ? "w-10" : "w-16";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex-1">{children}</div>

        <div className={`asideright fixed right-0 top-0 h-screen ${asideWidth} flex flex-col`}>
          <div className="clip-path-bottom h-[30vh]" style={{ backgroundColor: "#575757" }}>
            <div className="aside-hover">Cinza</div>
          </div>

          <div className="aside-block" style={{ backgroundColor: "#ffffff", marginTop: "-50px" }}>
            <div className="aside-hover" style={{ color: "#000" }}>Branco</div>
          </div>

          <div className="aside-block" style={{ backgroundColor: "#ED4242" }}>
            <div className="aside-hover">Vermelho</div>
          </div>

          <div className="aside-block" style={{ backgroundColor: "#4292ED" }}>
            <div className="aside-hover">Azul</div>
          </div>

          <div className="aside-block black clip-path-top h-[40vh]" style={{ backgroundColor: "#000000" }}>
            <div className="aside-hover">Preto</div>
          </div>
        </div>

      </body>
    </html>
  );
}
